### ISSUE TITLE
SNES9X 1.61 BS-X autodetect issue.

### ISSUE THREAD

**Issue by KiddoCabbusses** [Krokodyl/koi-wa-balance#1]
Hi! I just patched the ROM and checked it out.

Recent versions of SNES9X have a setup for automatic detection of 8M Pack downloads (Refering to them as "BS games" is technically easier but, uh, sounds wrong, lol) and will automatically boot up the BS-X ROM with the data loaded into memory if you have everything set up properly and try loading it. Unfortunately, this gets complicated when dealing with Satellaview ROM hacks of any sort.

The long and short of it is, SNES9X detects the game and tries to boot it in BS-X. However, since the ROM has been expanded to 2mb (No memory packs larger than 1mb existed) the game will go into BS-X Error 32 when attempting to boot it up. I'm going to assume you never intended for the translated ROM to interact with BS-X in the first place (Although I personally find that tragic, it's probably beyond theoretical possibility anyway...). I've managed to get the ROM to boot and play by stripping the header data, but my method is rather inelegant, so I figured I'd just report it here and see if you'd like to implement a more professional solution.

Presumably this issue may affect other emulators that attempt to automatically detect memory pack downloads.

**Comment by Krokodyl** [comment]
Hey!

That's very good to know. It's true that I don't have any knowledge of the behavior of emulating BS games.
I am using two emulators that are a bit dated but that have very good features for debugging and they both run the original rom and the patched rom with the same settings.
* bsnes v05 (Aug 18 2019)
Loading works with:
-- Menu : Load BS-X Cartridge
-- Base Cartridge : BS-X BIOS (English) [No DRM] [2016 v1.3].sfc
-- Sloft Cartridge : Patched rom
The patched rom needs to have the correct internal size and checksum in order to work.
With this way of loading, it goes into the Satellaview OS and you have to do "Load Stored Data".

* Snes9X v1.51.ep10r1 - Geiger's Snes9x Debugger
Loads the patched rom regardless of the correct header.

I'm going to check recent emulators and try to find a universal fix for this issue. It's my mistake for not doing the due diligence of doing that before release.
I appreciate your feedback very much.

**Comment by Krokodyl** [comment]
For the time being, I modified the header to have the rom loaded as a SNES game:
https://github.com/Krokodyl/koi-wa-balance/tree/main/patch/snes
Let me know if it works.

**Comment by TheShadowRunner** [comment]
Having this issue with the patch posted on RHDN:
![satbad](https://user-images.githubusercontent.com/1895340/188822607-1bd7494c-3c6f-4d36-8652-ead25674ec63.png)
Isn't it possible to fix loading via BSX interface (for BSnes & SD2SNES) ?

**Comment by Krokodyl** [comment]
> Having this issue with the patch posted on RHDN: ![satbad](https://user-images.githubusercontent.com/1895340/188822607-1bd7494c-3c6f-4d36-8652-ead25674ec63.png) Isn't it possible to fix loading via BSX interface (for BSnes & SD2SNES) ?

Can you try this other patch : https://github.com/Krokodyl/koi-wa-balance/tree/main/patch/snes

**Comment by TheShadowRunner** [comment]
Yes, that other patch works on SD2SNES, the former .BS one doesn't (Error 09 above).
It'd still be nice if you could fix loading from the BS interface, it adds that authentic BS experience ^^
Thanks.

**Comment by Krokodyl** [comment]
Hey!
I worked on it a bit.
I made a new patch: [https://github.com/Krokodyl/koi-wa-balance/tree/main/patch/1.1](https://github.com/Krokodyl/koi-wa-balance/tree/main/patch/1.1)

Can you test if it works as a regular BS game?
If so I'll update it on RHDN.
Thank you.

**Comment by TheShadowRunner** [comment]
This one runs as regular BS game alright, thank you !

**Comment by KiddoCabbusses** [comment]
Just tested the new patch. Nice job bringing it back down to the 1.0mb filesize! I wish that was possible with Radical Dreamers, as that translation has a very similar issue from what I remember.

If you're ever taking an interest in translating more Satellaview games, feel free to let me know.

**Comment by Krokodyl** [comment]
Thank you both!
